//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioJG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_celularesEntities : DbContext
    {
        public db_celularesEntities()
            : base("name=db_celularesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_celulares> tbl_celulares { get; set; }
        public virtual DbSet<tbl_operadora> tbl_operadora { get; set; }
        public virtual DbSet<tbl_usuarios> tbl_usuarios { get; set; }
    }
}
