//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioJG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_celulares
    {
        public int id { get; set; }
        public string modelo { get; set; }
        public string marca { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> idOperadora { get; set; }
    
        public virtual tbl_operadora tbl_operadora { get; set; }
    }
}
